version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: audit-trail
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audit-trail
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
